# Generated by Django 5.0.6 on 2025-04-15 15:19

import dairy_collection.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FatBasedPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fat_percentage', models.DecimalField(decimal_places=1, help_text='Fat percentage (e.g., 3.5)', max_digits=3, unique=True)),
                ('price', models.DecimalField(decimal_places=2, help_text='Price per liter in rupees', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Fat Based Price',
                'verbose_name_plural': 'Fat Based Prices',
                'ordering': ['fat_percentage'],
            },
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfid_number', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(error_messages={'invalid': 'Enter a valid 10-digit phone number.', 'unique': 'This phone number is already registered.'}, help_text='Enter a 10-digit mobile number starting with 6, 7, 8, or 9', max_length=10, unique=True, validators=[dairy_collection.models.validate_phone_length])),
                ('bank_account_number', models.CharField(max_length=18, unique=True, validators=[django.core.validators.RegexValidator(message='Bank account number must be between 9 and 18 digits', regex='^\\d{9,18}$')])),
                ('ifsc_code', models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='IFSC code must be valid format: 4 letters followed by 0 and 6 alphanumeric characters', regex='^[A-Z]{4}0[A-Z0-9]{6}$')])),
                ('address', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_collection_farmer', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='MilkRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milk_type', models.CharField(choices=[('cow', 'Cow Milk'), ('buffalo', 'Buffalo Milk')], max_length=10)),
                ('min_fat', models.DecimalField(decimal_places=1, help_text='Minimum fat percentage for this rate', max_digits=3)),
                ('max_fat', models.DecimalField(decimal_places=1, help_text='Maximum fat percentage for this rate', max_digits=3)),
                ('base_rate', models.DecimalField(decimal_places=2, help_text='Base rate per liter', max_digits=5)),
                ('fat_multiplier', models.DecimalField(decimal_places=2, help_text='Rate multiplier per 0.1% fat', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['milk_type', 'min_fat'],
                'unique_together': {('milk_type', 'min_fat', 'max_fat')},
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_collection.farmer')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processed', 'Processed'), ('failed', 'Failed')], max_length=20)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_collection.farmer')),
            ],
        ),
        migrations.CreateModel(
            name='MilkCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('milk_type', models.CharField(choices=[('cow', 'Cow Milk'), ('buffalo', 'Buffalo Milk')], max_length=10)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fat_content', models.DecimalField(decimal_places=1, max_digits=3)),
                ('snf_content', models.DecimalField(decimal_places=1, default=0.0, max_digits=3)),
                ('price_per_liter', models.DecimalField(decimal_places=2, max_digits=5)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=10)),
                ('sms_sent', models.BooleanField(default=False)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_collection.farmer')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('farmer', 'date', 'session')},
            },
        ),
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_quantity', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('average_fat', models.DecimalField(decimal_places=1, max_digits=3)),
                ('average_snf', models.DecimalField(decimal_places=1, max_digits=3)),
                ('collection_count', models.IntegerField()),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dairy_collection.farmer')),
            ],
            options={
                'ordering': ['-start_date'],
                'unique_together': {('farmer', 'start_date')},
            },
        ),
    ]
